// <auto-generated />
using System;
using BibliothequeLIPAJOLI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliothequeLIPAJOLI.Migrations
{
    [DbContext(typeof(BibliothequeLIPAJOLIContext))]
    partial class BibliothequeLIPAJOLIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("BibliothequeLIPAJOLI.Edition", b =>
                {
                    b.Property<int>("EditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnneeEdition")
                        .HasColumnType("TEXT");

                    b.Property<int>("LivreID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomEditeur")
                        .HasColumnType("TEXT");

                    b.HasKey("EditionID");

                    b.HasIndex("LivreID");

                    b.ToTable("Edition", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Adresse", b =>
                {
                    b.Property<int>("AdresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePostale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("AdresseID");

                    b.ToTable("Adresse", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Emprunt", b =>
                {
                    b.Property<int>("EmpruntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateEmprunt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateProbableRetour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExemplaireID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsagerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmpruntID");

                    b.HasIndex("ExemplaireID");

                    b.HasIndex("UsagerID");

                    b.ToTable("Emprunt", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Exemplaire", b =>
                {
                    b.Property<int>("ExemplaireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAchat")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fournisseur")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NbExemplaire")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Reference")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExemplaireID");

                    b.HasIndex("EditionID");

                    b.ToTable("Exemplaire", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Livre", b =>
                {
                    b.Property<int>("LivreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Annee")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategorieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EnStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Langue")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NombrePages")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("LivreID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Livre", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Personne", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Personne", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Redaction", b =>
                {
                    b.Property<int>("LivreID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuteurID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("LivreID", "AuteurID");

                    b.HasIndex("LivreID", "AuteurID")
                        .IsUnique();

                    b.ToTable("Redaction", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.UsagerAdresse", b =>
                {
                    b.Property<int>("UsagerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdresseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TypeAdresse")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsagerID", "AdresseID");

                    b.HasIndex("AdresseID");

                    b.ToTable("UsagerAdresse", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Usager", b =>
                {
                    b.HasBaseType("BibliothequeLIPAJOLI.Models.Personne");

                    b.Property<int>("Defaillance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroAbonne")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.ToTable("Usager", (string)null);
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Edition", b =>
                {
                    b.HasOne("BibliothequeLIPAJOLI.Models.Livre", "Livre")
                        .WithMany("Editions")
                        .HasForeignKey("LivreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Emprunt", b =>
                {
                    b.HasOne("BibliothequeLIPAJOLI.Models.Exemplaire", "Exemplaire")
                        .WithMany("Emprunts")
                        .HasForeignKey("ExemplaireID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliothequeLIPAJOLI.Models.Usager", "Usager")
                        .WithMany("Emprunts")
                        .HasForeignKey("UsagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exemplaire");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Exemplaire", b =>
                {
                    b.HasOne("BibliothequeLIPAJOLI.Edition", "Edition")
                        .WithMany("Exemplaires")
                        .HasForeignKey("EditionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Redaction", b =>
                {
                    b.HasOne("BibliothequeLIPAJOLI.Models.Livre", "Livre")
                        .WithMany("Redactions")
                        .HasForeignKey("LivreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.UsagerAdresse", b =>
                {
                    b.HasOne("BibliothequeLIPAJOLI.Models.Adresse", "Adresse")
                        .WithMany("UsagerAdresses")
                        .HasForeignKey("AdresseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliothequeLIPAJOLI.Models.Usager", "Usager")
                        .WithMany("UsagerAdresses")
                        .HasForeignKey("UsagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresse");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Usager", b =>
                {
                    b.HasOne("BibliothequeLIPAJOLI.Models.Personne", null)
                        .WithOne()
                        .HasForeignKey("BibliothequeLIPAJOLI.Models.Usager", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Edition", b =>
                {
                    b.Navigation("Exemplaires");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Adresse", b =>
                {
                    b.Navigation("UsagerAdresses");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Exemplaire", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Livre", b =>
                {
                    b.Navigation("Editions");

                    b.Navigation("Redactions");
                });

            modelBuilder.Entity("BibliothequeLIPAJOLI.Models.Usager", b =>
                {
                    b.Navigation("Emprunts");

                    b.Navigation("UsagerAdresses");
                });
#pragma warning restore 612, 618
        }
    }
}
